replicaCount: 1

fastapi:
  image: enterprise/fastapi-triton:latest
  imagePullPolicy: IfNotPresent
  servicePort: 8080
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: 500m
      memory: 1Gi

triton:
  image: nvcr.io/nvidia/tritonserver:23.10-py3
  modelRepoPath: /models
  resources:
    limits:
      nvidia.com/gpu: 1
    requests:
      cpu: 1000m
      memory: 4Gi
