apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise-deploy.fullname" . }}-triton
spec:
  selector:
    app: {{ include "enterprise-deploy.fullname" . }}-triton
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
