apiVersion: v1
kind: Service
metadata:
  name: {{ include "enterprise-deploy.fullname" . }}-fastapi
spec:
  selector:
    app: {{ include "enterprise-deploy.fullname" . }}-fastapi
  ports:
    - protocol: TCP
      port: {{ .Values.fastapi.servicePort }}
      targetPort: {{ .Values.fastapi.servicePort }}
  type: ClusterIP
